import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import {Inter} from 'next/font/google';
import Navbar from "@/components/main/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-y-scroll overflow-x-hidden`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
