
export const lastshop  = [
    {
        name:'sac rose',
        image:'/sac rouge plus bande.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'out of stock',
    },
    {
        name:'sac mauve',
        image:'/sac mauve.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'out of stock',
    },
    {
        name:'sac noir',
        image:'/sac beige.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'out of stock',
    },
    {
        name:'sac noir',
        image:'/sacrose.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'out of stock',
    },

    {
        name:'sac vert',
        image:'/sacvert.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'available',
    },
    {
        name:'sac noir',
        image:'/sacbeige.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'available',
    },
    {
        name:'sac rougenoir',
        image:'/sacrougenoir.jpeg',
        height :300,
        width:300,
        price: 17000,
        sale: 79,
        quantity:'available',
    },
    {
        name:'sac bleu',
        image:'/sacbleu.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },

    {
        name:'sac rouge',
        image:'/sac rouge.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },{
        name:'sac Multicolor',
        image:'/sac beige multicolor.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },{
        name:'sac noir',
        image:'/sac rouge noir.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },{
        name:'sac noir',
        image:'/sac rouge noir.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },
]