
export const lastshop  = [
    {
        name:'sac noir',
        image:'/sacnoirfleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'out of stock',
    },
    {
        name:'sac noir',
        image:'/sacnoirfleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'out of stock',
    },
    {
        name:'sac noir',
        image:'/sacnoirfleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'out of stock',
    },
    {
        name:'sac noir',
        image:'/sacnoirfleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'out of stock',
    },

    {
        name:'sac noir',
        image:'/sacrosefleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'available',
    },
    {
        name:'sac noir',
        image:'/sacrosefleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'available',
    },
    {
        name:'sac noir',
        image:'/sacrosefleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 79,
        quantity:'available',
    },
    {
        name:'sac noir',
        image:'/sacbleufleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },

    {
        name:'sac noir',
        image:'/sacbleufleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },{
        name:'sac noir',
        image:'/sacbleufleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },{
        name:'sac noir',
        image:'/sacbleufleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },{
        name:'sac noir',
        image:'/sacbleufleur.jpeg',
        height :200,
        width:200,
        price: 17000,
        sale: 49,
        quantity:'available',
    },
]